### PR TITLE
Escape apostrophes in title, artist or album names

### PR DESCRIPTION
**Pull request by nf1973**
Tracks having apostrophes in the Title, Artist or Album names were failing to be found in the search. Escaping these characters avoids the issue.

### CODE REVIEW

**Comment by nf1973** [comment]
Hi, yes, I checked it with your playlist and it works - but I noticed that in my PR I had changed the column numbers so i assume this is the issue. I will try to submit a new PR.

The output was:

`N°1 | Day \'N\' Nite (Nightmare) | Kid Cudi | Man On The Moon: The End Of Day (Int\'l Version) => 1443522106
Song 1443522106 added to playlist spotify2am_-_test_apostrophes!

N°2 | Welcome To Jamrock | Damian Marley | Welcome to Jamrock => 1440723209
Song 1440723209 added to playlist spotify2am_-_test_apostrophes!

N°3 | It Ain\'t Over \'Til It\'s Over | Lenny Kravitz | Mama Said => 721256152
Song 721256152 added to playlist spotify2am_-_test_apostrophes!

N°4 | THIS YEAR (Blessings) - Remix | Victor Thompson, Gunna, Ehis \'D\' Greatest | THIS YEAR (Blessings) [Remix] => 1711507557
Song 1711507557 added to playlist spotify2am_-_test_apostrophes!

N°5 | Don\'t Stop \'Til You Get Enough | Michael Jackson | Off the Wall => 1580800110
Song 1580800110 added to playlist spotify2am_-_test_apostrophes!

 - STAT REPORT -
Playlist Songs: 5
Converted Songs: 5
Failed Songs: 0
Playlist converted at 100%
`

**Comment by nf1973** [comment]
Also, because I was having to hardcode the connection settings because of terminal character limit for pasting, I also added a way to store them in files instead.

This version will read and use token.dat, media_user_token.dat and cookies.dat if they exist (and prompt the user for them, as in the original version, if the files don't exist).

Hope it makes sense for you!

**Comment by nf1973** [comment]
Just added a change that will avoid encoding issues with non-western character sets when writing the no_results.txt file

**Review by therealmarius — APPROVED** [review]

**Comment by therealmarius** [comment]
Thanks for all of your work!

**Pull request merged**
